version: "3.8"

services:
  ledger_service:
    container_name: ledger_service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - postgesql
    restart: always
    volumes:
      - ./:/app
    networks:
      - microservice_network

  postgesql:
    image: postgres:13-alpine
    container_name: postgesql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=txn_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - microservice_network

networks:
  microservice_network:
    driver: bridge